TycoonHost: "http://127.0.0.1"
TycoonPort: ":2377"
SwarmHost: "http://192.168.11.57"
SwarmPort: ":2370"
EtcdPath: "http://192.168.11.57:2379"
LogLevel: "debug"
#LogLevel:"panic","fatal","error","warn"/"warning","info","debug"
LogPath: "./log"